name: Test Automation with Allure Report
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
permissions:
  contents: write
 
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Run tests
      run: mvn clean test -Ptest-all
      continue-on-error: true
    
    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    
    - name: Build Allure report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        allure_results: target/allure-results
        allure_history: allure-history
        keep_reports: 20
    
    - name: Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
